#include <iostream>
#include <iomanip>
#include "Creature.hpp"
#include "Character.hpp"
#include "Priest.hpp"
#include "Hunter.hpp"
#include "Warrior.hpp"
#include "Mage.hpp"
#include "Rogue.hpp"
#include "NpCharacter.hpp"
#include "Buff.hpp"
#include "Debuff.hpp"
#include "DebuffBurning.hpp"
#include "DebuffBleeding.hpp"
#include "DebuffPoisoned.hpp"
#include "EgoShadow.hpp"
#include "GnomeRath.hpp"
#include "GnomeBeth.hpp"
#include "BoarColossal.hpp"
#include "GoblinPaladin.hpp"
#include "DemonAztras.hpp"
#include "Interval.hpp"
#include "Conflict5.hpp"
#include "Conflict6.hpp"
#include "Conflict7.hpp"
#include "Conflict8.hpp"

void Act2(std::vector <Character*>& players, Character*& luna);