#include <iostream>
#include <iomanip>
#include "Creature.hpp"
#include "Character.hpp"
#include "Priest.hpp"
#include "Hunter.hpp"
#include "CharacterCreation.hpp"
#include "Warrior.hpp"
#include "Mage.hpp"
#include "Rogue.hpp"
#include "NpCharacter.hpp"
#include "Buff.hpp"
#include "Debuff.hpp"
#include "DebuffBurning.hpp"
#include "DebuffBleeding.hpp"
#include "DebuffPoisoned.hpp"
#include "Saberwolf.hpp"
#include "SaberwolfAlpha.hpp"
#include "Chimera.hpp"
#include "GoblinWarlock.hpp"
#include "InjuriedSeiren.hpp"
#include "Interval.hpp"
#include "Conflict9.hpp"
#include "Conflict10.hpp"
#include "Conflict11.hpp"

void Act3(std::vector <Character*>& players, Character*& qing);